#!/usr/bin/env python3
"""Parse plasmid .gb (GenBank) files, extract feature table, auto-fill/update plasmid card.
Dependency: biopython.
Usage:
  python tools/gb_annotate.py lims/plasmids/PLA-0042-*/map.gb        # print feature table
  python tools/gb_annotate.py lims/plasmids/PLA-0042-*/map.gb --write # write back to card.md in same dir

It does: (1) read .gb length/topology/features (CDS/promoter/misc_feature etc.); (2) insert/update
a "## Sequence Features (auto)" section in card.md plus length/topology/features fields in frontmatter;
(3) detect resistance genes (AmpR/KanR/PuroR...) and fill resistance. Never overwrites your hand-written content.
"""
import sys, os, re, argparse, glob
from Bio import SeqIO

ap=argparse.ArgumentParser()
ap.add_argument("gb"); ap.add_argument("--write", action="store_true")
a=ap.parse_args()
gb_path=glob.glob(a.gb)[0] if glob.glob(a.gb) else a.gb
rec=SeqIO.read(gb_path, "genbank")
length=len(rec.seq)
topology=rec.annotations.get("topology","")

RES={"ampr":"ampicillin","bla":"ampicillin","kanr":"kanamycin","neor":"kanamycin/G418",
     "puror":"puromycin","pac":"puromycin","hygr":"hygromycin","cmr":"chloramphenicol",
     "specr":"spectinomycin","zeor":"zeocin","blastr":"blasticidin"}
feats=[]; resistances=set()
for f in rec.features:
    if f.type in ("source",): continue
    label=(f.qualifiers.get("label") or f.qualifiers.get("gene") or
           f.qualifiers.get("product") or [f.type])[0]
    start=int(f.location.start)+1; end=int(f.location.end)
    strand="+" if f.location.strand in (1,None) else "-"
    feats.append((f.type,label,start,end,strand))
    for k,v in RES.items():
        if k in label.lower().replace(" ",""): resistances.add(v)

# print table
print(f"# {os.path.basename(gb_path)}  length={length} bp  topology={topology}")
print(f"{'type':<14}{'label':<28}{'start':>8}{'end':>8}  strand")
for t,l,s,e,st in feats:
    print(f"{t:<14}{l[:27]:<28}{s:>8}{e:>8}  {st}")
if resistances: print("Detected resistance:", ", ".join(sorted(resistances)))

if not a.write:
    sys.exit(0)

# ---- write back into card.md ----
card=os.path.join(os.path.dirname(gb_path),"card.md")
if not os.path.exists(card):
    print("No card.md found in same directory, skipping write."); sys.exit(0)
txt=open(card).read()

# build auto block
lines=["## Sequence Features (auto)  <!-- generated by gb_annotate.py, do not edit this section -->",
       f"- length: {length} bp  topology: {topology}",
       "",
       "| type | label | start | end | strand |","|---|---|---|---|---|"]
for t,l,s,e,st in feats:
    lines.append(f"| {t} | {l} | {s} | {e} | {st} |")
auto_block="\n".join(lines)

# replace existing auto block or append
pat=re.compile(r"## Sequence Features \(auto\).*?(?=\n## |\Z)", re.S)
if pat.search(txt):
    txt=pat.sub(auto_block+"\n", txt)
else:
    txt=txt.rstrip()+"\n\n"+auto_block+"\n"

# update frontmatter length + resistance (only if present as empty/placeholder)
def set_fm(txt, key, val):
    m=re.search(rf"^{key}:.*$", txt, re.M)
    line=f"{key}: {val}"
    if m: return txt[:m.start()]+line+txt[m.end():]
    # insert after 'type:' line inside frontmatter
    return re.sub(r"(^type:.*$)", r"\1\n"+line, txt, count=1, flags=re.M)

txt=set_fm(txt,"length",f"{length}")
txt=set_fm(txt,"topology",topology)
if resistances:
    txt=set_fm(txt,"resistance","["+", ".join(sorted(resistances))+"]")
open(card,"w").write(txt)
print(f"-> Updated {card} ({len(feats)} features)")
